# -*- coding: utf-8 -*-
"""ChatBot using python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tln8xsE5Pd1Ntua0rLewAeizs9fU0xTW
"""

from nltk.chat.util import Chat, reflections
#default message at the start of chat
print("Hi, cbot is here to help you.  \nPlease type lowercase English language to start a conversation.\nType quit to leave ")
#Create Chat Bot
chat = Chat(pairs, reflections)
#Start conversation
chat.converse()
pairs = [
    [
        r"(.*)my name is (.*)",
        ["Hello %2, how can I assist you today?",]
    ],
    [
        r"(.*)help(.*)",
        ["I'm here to help.",]
    ],
     [
        r"(.*) your name ?",
        ["I am a chatbot, you can call me ChatAssistant.",]
    ],
    [
        r"how are you (.*) ?",
        ["I'm programmed to function well, thank you.", "I'm doing fine, thanks for asking!"]
    ],
    [
        r"sorry (.*)",
        ["No problem.", "It's okay, no need to apologize.",]
    ],
    [
        r"i'm (.*) (good|well|okay|ok)",
        ["That's great to hear!", "Good to know, how can I assist you further?",]
    ],
    [
        r"(hi|hey|hello|hola|holla)(.*)",
        ["Hello! How can I help you today?", "Hey there! What can I do for you?",]
    ],
    [
        r"what (.*) want ?",
        ["Let's discuss how I can assist you.",]

    ],
    [
        r"(.*)created(.*)",
        ["I was created by a developer using Python's programming language.", "My origins are coded, created by a programmer.",]
    ],
    [
        r"(.*) (location|city) ?",
        ["I don't have a physical location, but I'm here to assist you.",]
    ],
    [
        r"(.*)raining in (.*)",
        ["I don't have real-time weather information, but I can provide general details.", "I'm not equipped to give current weather updates, but I can help with other queries.",]
    ],
    [
        r"how (.*) health (.*)",
        ["I'm a computer program, so I don't have health. How can I assist you?",]
    ],
    [
        r"(.*)(sports|game|sport)(.*)",
        ["I don't have personal preferences, but I can provide information on various sports.",]
    ],
    [
        r"who (.*) (Cricketer|Batsman)?",
        ["I don't have personal opinions, but a well-known cricketer is Virat Kohli.",]
    ],
     [
        r"(.*)(programming|code|coding)(.*)",
        ["I'm familiar with various programming languages. How can I assist you with coding?",]
    ],
    [
        r"(.*)favorite programming language(.*)",
        ["I don't have personal preferences, but I can help with Python, JavaScript, Java, and more.",]
    ],
    [
        r"(.*) recommend (.*) programming language",
        ["The best programming language depends on your goals. I can help you decide based on your needs.",]
    ],
    [
        r"(.*)debug(.*)",
        ["Debugging is a common challenge. Share your code, and I'll do my best to help you find the issue.",]
    ],
    [
        r"(.*)learn programming(.*)",
        ["There are many resources available online for learning programming. I can suggest some based on your interests.",]
    ],
    [
        r"(.*)version control(.*)",
        ["Version control is essential for collaborative coding. Git is a popular tool for managing versions.",]
    ],
    [
        r"(.*)web development(.*)",
        ["Web development involves frontend and backend technologies. Do you have a specific question about web development?",]
    ],
    [
        r"(.*)database(.*)",
        ["Databases are crucial for storing and retrieving data. SQL and NoSQL databases are common choices.",]
    ],
    [
        r"(.*)API(.*)",
        ["An API (Application Programming Interface) allows different software systems to communicate. How can I help you with APIs?",]
    ],
    [
        r"(.*)Python(.*)",
        ["Python is a versatile language used in web development, data science, and more. How can I assist you with Python?",]
    ],
    [
        r"(.*)Java(.*)",
        ["Java is a widely-used programming language. What do you need help with in Java?",]
    ],
    [
        r"(.*)cooking(.*)recipe(.*)",
        ["I can help you with cooking recipes! What type of cuisine or dish are you interested in?",]
    ],
    [
        r"(.*)favorite dish(.*)",
        ["I don't have personal preferences, but I can suggest various dishes. What are you in the mood for?",]
    ],
    [
        r"(.*)quick and easy recipes(.*)",
        ["Sure! How much time do you have, and do you have any specific dietary preferences?",]
    ],
    [
        r"(.*)school(.*)work(.*)",
        ["I can assist with school-related queries. What subject or specific topic do you need help with?",]
    ],
    [
        r"(.*)study tips(.*)",
        ["Effective study habits include setting a schedule, staying organized, and taking breaks. How can I assist you further?",]
    ],
    [
        r"(.*)relationship(.*)",
        ["Relationships can be complex. If you'd like, you can share more details, and I can offer some general advice.",]
    ],
    [
        r"(.*)communication(.*)",
        ["Clear communication is crucial in relationships. Is there a specific aspect you'd like advice on?",]
    ],
    [
        r"(.*)resolve conflicts(.*)",
        ["Conflict resolution involves open communication and understanding. How can I help you navigate a specific situation?",]
    ],
    [
        r"(.*)self-care(.*)",
        ["Taking care of yourself is important. What specific self-care practices are you interested in?",]
    ],
    [
        r"(.*)stress relief(.*)",
        ["Managing stress is crucial. Try practicing some meditation, outdoor morning walks to avoid stress.",]
    ],
    [
        r"quit",
        ["Goodbye for now. Feel free to return anytime.", "It was nice interacting with you. See you soon!"]
    ],
    [
        r"(.*)",
        ["I'm sorry, I couldn't understand that. Please try rephrasing your message."]
    ],
]